# Generated by Django 4.0.1 on 2022-01-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
    ]
