# Generated by Django 4.0.1 on 2022-01-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220126_0513'),
    ]

    operations = [
    ]
